apiVersion: apps/v1
kind: Deployment
metadata:
  name: workshop-app
  labels:
    app: workshop-app
spec:
  replicas: 1
  revisionHistoryLimit: 2
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: workshop-app
  template:
    metadata:
      labels:
        app: workshop-app
    spec:
      containers:
        - name: app
          image: ghcr.io/aihpi/workshop-agentic-rag:sha-71d6503
          ports:
            - containerPort: 8000
          env:
            - name: DATA_KB_DOCS_DIR
              value: /data/kb_docs
            - name: DATA_RAW_DIR
              value: /data/data_raw
          envFrom:
            - secretRef:
                name: workshop-app-secrets
          volumeMounts:
            - name: kb-docs
              mountPath: /data/kb_docs
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "2Gi"
              cpu: "1000m"
      volumes:
        - name: kb-docs
          persistentVolumeClaim:
            claimName: workshop-app-kb-docs
