apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: workshop-app-kb-docs
  labels:
    app: workshop-app
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 20Gi
